import { Link } from "react-router-dom";

export default function PrivacyPolicyPDB() {
  return (
    <main className="min-h-screen bg-[#0a0f1c] text-zinc-100">
      <section className="max-w-4xl mx-auto px-6 md:px-10 py-16 md:py-20">
        <div className="mb-10">
          <Link
            to="/"
            className="inline-flex items-center text-sm text-zinc-400 hover:text-white transition-colors"
          >
            ← Back to home
          </Link>
        </div>

        <div className="max-w-3xl">
          <p className="text-sm text-zinc-500 mb-4 tracking-wide">
            Privacy Policy
          </p>

          <h1 className="text-4xl md:text-5xl font-semibold leading-tight mb-6">
            PDB Privacy Policy
          </h1>

          <p className="text-zinc-400 text-base md:text-lg leading-8 mb-10">
            This Privacy Policy explains how PDB handles user information when
            using the app.
          </p>

          <div className="space-y-10 text-zinc-300 leading-8">
            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                1. Information We Collect
              </h2>
              <p>
                PDB may process limited information necessary for the game to
                function properly. This may include temporary player names,
                anonymous authentication identifiers generated by Firebase,
                room data, multiplayer session state, votes, and user-generated
                responses submitted during gameplay.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                2. How Information Is Used
              </h2>
              <p>
                The collected information is used only to provide and maintain
                the gameplay experience, including creating and joining rooms,
                synchronizing multiplayer sessions, storing match progress, and
                supporting game features such as freestyle answers, voting, and
                score tracking.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                3. User-Generated Content
              </h2>
              <p>
                PDB allows players to create custom text responses during
                gameplay. These responses are visible to other players within
                the same game session and may be temporarily stored to support
                multiplayer functionality.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                4. Third-Party Services
              </h2>
              <p>
                The app uses Firebase services, including Authentication and
                Firestore, to support anonymous sign-in and real-time multiplayer
                data storage. These services may process technical data required
                for their operation in accordance with their own policies.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                5. Data Sharing
              </h2>
              <p>
                We do not sell personal information. Information is not shared
                with third parties except when required for the operation of the
                app through trusted infrastructure providers such as Firebase.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                6. Data Retention
              </h2>
              <p>
                Some game-related data may be stored temporarily to maintain
                active rooms and multiplayer functionality. Inactive or expired
                room data may be removed periodically as part of normal app
                operation.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                7. Children’s Privacy
              </h2>
              <p>
                The app is not directed to children under the age required by
                applicable law in their region.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                8. Security
              </h2>
              <p>
                Reasonable measures are taken to protect the information used by
                the app, but no method of transmission or storage is completely
                secure.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                9. Changes to This Policy
              </h2>
              <p>
                This Privacy Policy may be updated from time to time. Any changes
                will be reflected on this page.
              </p>
            </section>

            <section>
              <h2 className="text-xl md:text-2xl font-semibold text-zinc-100 mb-3">
                10. Contact
              </h2>
              <p>
                If you have questions about this Privacy Policy, you can contact:
              </p>

              <p className="mt-2 text-zinc-100 font-medium">
                shai.kohn.dev@gmail.com
              </p>
            </section>
          </div>

          <p className="text-sm text-zinc-500 mt-12">
            Last updated: May 2026
          </p>
        </div>
      </section>
    </main>
  );
}